targets:
  $default:
    builders:
      reactive_forms_generator:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/integration/*
            - test/integration/**/*

builders:
  reactive_forms_generator:
    import: "package:reactive_forms_generator/builder.dart"
    builder_factories: [ "reactiveFormsGenerator" ]
    build_extensions: { ".dart": [ ".gform.dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before: [ "freezed|freezed", "json_serializable|json_serializable" ]